packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react:
    "next": 15.4.5
    "next-themes": 0.4.6
    "@tanstack/react-query": 5.85.5
  web3:
    "@solana/web3.js": 1.98.4
    "@solana/wallet-adapter-base": 0.9.27
    "@solana/wallet-adapter-react": 0.15.39
    "@solana/wallet-adapter-react-ui": 0.9.39
    "@solana/spl-token": 0.4.13
    "@coral-xyz/anchor": 0.31.1
    
